/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;

import modelo.modeloCategorias;
import controle.controlCatego;
import db.Conexao;
import java.util.ArrayList;
import javax.swing.ListSelectionModel;
import modelo.modeloTabela;

public class Categorias extends javax.swing.JFrame {

    Conexao conectaCat=new Conexao();
    controlCatego control=new controlCatego();
    modeloCategorias mod=new modeloCategorias();
    
    public Categorias() {
        initComponents();
        preenchetabelaCategorias("select * from tbl_categorias order by nome_cat");
    }
    
    public void preenchetabelaCategorias(String sql){
        ArrayList dados=new ArrayList();
            //VETOR COLUNAS COM OS CABEÇALHOS
            String[] colunas=new String[]{"ID","Categoria","Descrição"};
            //ABRINDO CONEXÃO
            conectaCat.conexao();
            //CRIANDO UMA CONSULTA SQL
            conectaCat.executaSQL(sql);
            try {
                //SETANDO O RESULTSET DA CONSULTA NA PRIMEIRA LINHA
                conectaCat.rs.first();
                //LOOP QUE VAI ALIMENTAR MEU VETOR DE OBJETO COM TODOS OS REGISTROS DA STRING SQL PASSADO ACIMA
                do{
                    dados.add(new Object[]{conectaCat.rs.getInt("id_Cat"),conectaCat.rs.getString("nome_Cat"),conectaCat.rs.getString("desc_cat")});                      
                //ENQUANTO EXISTIR REGISTRO PULE PARA A PROXIMA LINHA
                }while(conectaCat.rs.next());
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao preencher Tabela!"+e);
            }
            conectaCat.desconecta();
            modeloTabela tabela=new modeloTabela(dados, colunas);
            
            tabelaCategorias.setModel(tabela);
            tabelaCategorias.getColumnModel().getColumn(0).setPreferredWidth(40);
            tabelaCategorias.getColumnModel().getColumn(0).setResizable(true);
            tabelaCategorias.getColumnModel().getColumn(1).setPreferredWidth(150);
            tabelaCategorias.getColumnModel().getColumn(1).setResizable(true);
            tabelaCategorias.getColumnModel().getColumn(2).setPreferredWidth(110);
            tabelaCategorias.getColumnModel().getColumn(2).setResizable(true);
            
            tabelaCategorias.getTableHeader().setReorderingAllowed(false);
            tabelaCategorias.setAutoResizeMode(tabelaCategorias.AUTO_RESIZE_OFF);
            tabelaCategorias.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);   
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cxtCat = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cxtDesc = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCategorias = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        cxtPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Categorias");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel1.setText("Categoria:");

        cxtCat.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        cxtCat.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 11)); // NOI18N
        jLabel2.setText("Descrição:");

        cxtDesc.setFont(new java.awt.Font("Georgia", 0, 11)); // NOI18N
        cxtDesc.setEnabled(false);
        jScrollPane1.setViewportView(cxtDesc);

        tabelaCategorias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelaCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCategoriasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaCategorias);

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setToolTipText("Novo Cliente");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Save.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Cadastrar Cliente");
        btnSalvar.setEnabled(false);
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setToolTipText("Alterar Cliente");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setToolTipText("Excluir Cliente");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        cxtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxtPesquisaActionPerformed(evt);
            }
        });
        cxtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cxtPesquisaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cxtCat)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar))
                    .addComponent(btnExcluir)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cxtCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnNovo)
                    .addComponent(btnAlterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        cxtCat.setText("");
        cxtDesc.setText("");
        cxtCat.setEnabled(true);
        cxtDesc.setEnabled(true);
        cxtCat.requestFocus();
        
        btnNovo.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        if(cxtCat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Digite um nome para a categoria !");
            cxtCat.requestFocus();
        }else{
            mod.setCategoria(cxtCat.getText());
            mod.setDescricao(cxtDesc.getText());
            control.cadastraCat(mod);
            preenchetabelaCategorias("select * from tbl_categorias order by nome_cat");
            
            cxtCat.setText("");
            cxtDesc.setText("");
            cxtCat.setEnabled(false);
            cxtDesc.setEnabled(false);

            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        int alterar=JOptionPane.showConfirmDialog(null, "Tem certeza que deseja alterar os dados da categoria selecionada ?","Atenção",JOptionPane.YES_NO_OPTION);
        if(alterar==JOptionPane.YES_OPTION){
            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
            btnExcluir.setEnabled(true);
            btnAlterar.setEnabled(true);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        int excluir=JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir essa categoria?","Atenção",JOptionPane.YES_NO_OPTION);
        if(excluir==JOptionPane.YES_OPTION){       
            cxtCat.setText("");
            cxtDesc.setText("");
            cxtCat.setEnabled(false);
            cxtDesc.setEnabled(false);

            btnNovo.setEnabled(true);
            btnSalvar.setEnabled(false);
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void tabelaCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCategoriasMouseClicked
        if(evt.getClickCount()>1){
            cxtCat.setEnabled(true);
            cxtDesc.setEnabled(true);

            btnNovo.setEnabled(false);
            btnSalvar.setEnabled(false);
            btnExcluir.setEnabled(true);
            btnAlterar.setEnabled(true);
        }
    }//GEN-LAST:event_tabelaCategoriasMouseClicked

    private void cxtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cxtPesquisaKeyReleased
        preenchetabelaCategorias("select * from tbl_categorias where nome_cat like '%"+cxtPesquisa.getText()+"%'");
    }//GEN-LAST:event_cxtPesquisaKeyReleased

    private void cxtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxtPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cxtPesquisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categorias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categorias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JTextField cxtCat;
    private javax.swing.JTextPane cxtDesc;
    private javax.swing.JTextField cxtPesquisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaCategorias;
    // End of variables declaration//GEN-END:variables
}
