/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import javax.swing.JOptionPane;


public class Menu extends javax.swing.JFrame {
    
    //VARIAVEL QUE IRÁ RECEBER O ID DO USUARIO QUE LOGOU NO SISTEMA, PARA SER USADO FUTURAMENTE NO PDV E OUTROS METODOS
    int userLogado;
    
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menu_cad_cli = new javax.swing.JMenuItem();
        menu_cad_prod = new javax.swing.JMenuItem();
        menu_cad_forn = new javax.swing.JMenuItem();
        menu_cad_cat = new javax.swing.JMenuItem();
        menu_cad_lanc = new javax.swing.JMenuItem();
        menu_cad_moto = new javax.swing.JMenuItem();
        menu_cad_user = new javax.swing.JMenuItem();
        menu_vend_pdv = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        menu_finan = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        menu_rel = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        menu_ferr_agend = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hora: 22:00:00");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bem Vindo Administrador");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data: 24/24/2024");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Perfil: Administrador");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundos (69).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 408));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/note_edit.png"))); // NOI18N
        jMenu1.setText("Cadastros");

        menu_cad_cli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_cad_cli.setText("Clientes");
        menu_cad_cli.setEnabled(false);
        menu_cad_cli.setName("menu_cad_cli"); // NOI18N
        menu_cad_cli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cad_cliActionPerformed(evt);
            }
        });
        jMenu1.add(menu_cad_cli);

        menu_cad_prod.setText("Produtos");
        menu_cad_prod.setEnabled(false);
        menu_cad_prod.setName("menu_cad_prod"); // NOI18N
        jMenu1.add(menu_cad_prod);

        menu_cad_forn.setText("Fornecedores");
        menu_cad_forn.setEnabled(false);
        menu_cad_forn.setName("menu_cad_forn"); // NOI18N
        jMenu1.add(menu_cad_forn);

        menu_cad_cat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        menu_cad_cat.setText("Categorias");
        menu_cad_cat.setEnabled(false);
        menu_cad_cat.setName("menu_cad_cat"); // NOI18N
        menu_cad_cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cad_catActionPerformed(evt);
            }
        });
        jMenu1.add(menu_cad_cat);

        menu_cad_lanc.setText("Lanches");
        menu_cad_lanc.setEnabled(false);
        menu_cad_lanc.setName("menu_cad_lanc"); // NOI18N
        jMenu1.add(menu_cad_lanc);

        menu_cad_moto.setText("Motoboy");
        menu_cad_moto.setEnabled(false);
        menu_cad_moto.setName("menu_cad_lanc"); // NOI18N
        jMenu1.add(menu_cad_moto);

        menu_cad_user.setText("Usuários");
        menu_cad_user.setEnabled(false);
        menu_cad_user.setName("menu_cad_user"); // NOI18N
        menu_cad_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_cad_userActionPerformed(evt);
            }
        });
        jMenu1.add(menu_cad_user);

        jMenuBar1.add(jMenu1);

        menu_vend_pdv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shopping_cart_accept.png"))); // NOI18N
        menu_vend_pdv.setText("Caixa");
        menu_vend_pdv.setEnabled(false);
        menu_vend_pdv.setName("menu_vend_pdv"); // NOI18N

        jMenuItem10.setText("Nova Venda");
        menu_vend_pdv.add(jMenuItem10);

        jMenuItem11.setText("Consultar Vendas");
        menu_vend_pdv.add(jMenuItem11);

        jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem18.setText("Abertura de Caixa");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        menu_vend_pdv.add(jMenuItem18);

        jMenuBar1.add(menu_vend_pdv);

        menu_finan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculator.png"))); // NOI18N
        menu_finan.setText("Financeiro");
        menu_finan.setEnabled(false);
        menu_finan.setName("menu_finan"); // NOI18N

        jMenuItem12.setText("Contas a Pagar");
        menu_finan.add(jMenuItem12);

        jMenuItem13.setText("Contas a Receber");
        menu_finan.add(jMenuItem13);

        jMenuBar1.add(menu_finan);

        menu_rel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/chart.png"))); // NOI18N
        menu_rel.setText("Relatórios");
        menu_rel.setDoubleBuffered(true);
        menu_rel.setEnabled(false);
        menu_rel.setName("menu_rel"); // NOI18N
        jMenuBar1.add(menu_rel);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/process.png"))); // NOI18N
        jMenu4.setText("Ferramentas");

        jMenuItem14.setText("Calculadora");
        jMenu4.add(jMenuItem14);

        jMenuItem15.setText("Bloco de Notas");
        jMenu4.add(jMenuItem15);

        menu_ferr_agend.setText("Agenda");
        menu_ferr_agend.setEnabled(false);
        menu_ferr_agend.setName("menu_ferr_agend"); // NOI18N
        jMenu4.add(menu_ferr_agend);

        jMenuItem19.setText("Configurar Email");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem19);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/help.png"))); // NOI18N
        jMenu5.setText("Ajuda");
        jMenuBar1.add(jMenu5);

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/database_up.png"))); // NOI18N
        jMenu9.setText("Backup");

        jMenuItem17.setText("Backup Full SQL");
        jMenu9.add(jMenuItem17);

        jMenuBar1.add(jMenu9);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/info.png"))); // NOI18N
        jMenu6.setText("Sobre");
        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/close.png"))); // NOI18N
        jMenu7.setText("Sair");

        jMenuItem1.setText("Logoff");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem1);

        jMenuItem2.setText("Desligar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem2);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        Login abreLog=new Login();
        abreLog.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        int sair= JOptionPane.showConfirmDialog(null, "Tem certeza que deseja finalizar o sistema ?","Atenção",JOptionPane.YES_NO_OPTION);
        if(sair==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menu_cad_cliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cad_cliActionPerformed
        Clientes abreCli=new Clientes();
        abreCli.setVisible(true);
    }//GEN-LAST:event_menu_cad_cliActionPerformed

    private void menu_cad_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cad_userActionPerformed
        Usuarios abreUser=new Usuarios();
        abreUser.setVisible(true);
    }//GEN-LAST:event_menu_cad_userActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        aberturaCaixa abreCaixa=new aberturaCaixa();
        abreCaixa.setVisible(true);
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void menu_cad_catActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_cad_catActionPerformed
        Categorias abreCat=new Categorias();
        abreCat.setVisible(true);
    }//GEN-LAST:event_menu_cad_catActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        ConfigEmail abreMail=new ConfigEmail();
        abreMail.setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    public static javax.swing.JMenuItem menu_cad_cat;
    public static javax.swing.JMenuItem menu_cad_cli;
    public static javax.swing.JMenuItem menu_cad_forn;
    public static javax.swing.JMenuItem menu_cad_lanc;
    public static javax.swing.JMenuItem menu_cad_moto;
    public static javax.swing.JMenuItem menu_cad_prod;
    public static javax.swing.JMenuItem menu_cad_user;
    public static javax.swing.JMenuItem menu_ferr_agend;
    public static javax.swing.JMenu menu_finan;
    public static javax.swing.JMenu menu_rel;
    public static javax.swing.JMenu menu_vend_pdv;
    // End of variables declaration//GEN-END:variables
}
